### ISSUE TITLE
Síntesis de Gregorio Osorio

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-3-sintesis-Gregorio012#2]
[Sintesis_Gregorio Osorio Sarmiento.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Gregorio012/files/12500748/Sintesis_Gregorio.Osorio.Sarmiento.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
